package com.hustlink.backend.features.storage.model;

public enum StorageScope {
  CV, PROFILE_IMAGE, PROFILE_COVER, FEED_IMAGE, FEED_FILE, FEED_VIDEO, MESSAGE_IMAGE, MESSAGE_FILE, MESSAGE_VIDEO, COMPANY_LOGO, COMPANY_COVER, EVENT_COVER
}
